### ISSUE TITLE
404 error when trying to view certain Requim relics

### ISSUE THREAD

**Issue by Palkiaa** [EnKhayzo/warfarm#2]
I can navigate to these two (which are actually the same relic so this is duplicated for some reason):
https://enkhayzo.github.io/warfarm/prime/relics/Requiem
https://enkhayzo.github.io/warfarm/prime/relics/RequiemI

But these ones will show a 404 page not found:
https://enkhayzo.github.io/warfarm/prime/relics/RequiemIi
https://enkhayzo.github.io/warfarm/prime/relics/RequiemIii
https://enkhayzo.github.io/warfarm/prime/relics/RequiemIv

**Comment by EnKhayzo** [comment]
nevermind, thought i had solved the issue :\ working on it

**Comment by EnKhayzo** [comment]
should be fixed now ([375cfe4](https://github.com/EnKhayzo/warfarm/commit/375cfe44272acd6cb7272298a37b2b58a77e9c92)) thank you for reporting the issues and lmk if you find others
