### ISSUE TITLE
Farming sheet: Missions filter group by dropdown layout

### ISSUE THREAD

**Issue by Palkiaa** [EnKhayzo/warfarm#3]
This filter here has an option to group by that when clicking opens the dropdown but it overflows within the modal without any resizing
![image](https://github.com/user-attachments/assets/afd8151e-d3e4-4ef6-a266-5a38d71cf4c3)

Played around a bit in DevTools and disabled the `position: absolute` of the group by dropdown so might not be the best/exact solution but its usable now
![image](https://github.com/user-attachments/assets/4d0a25e2-6b56-404f-80ae-7654c0c55707)

**Comment by EnKhayzo** [comment]
fixed [23a2338](https://github.com/EnKhayzo/warfarm/commit/23a2338927f4767177b7cbdc7b43981103b8edf1) (i'm aware it doesn't disappear when you click on an option; i'm still deciding whether or not it's an intended feature, i'll fix in case it's not) ty
